version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "ST1001"
      - linters:
          - typecheck
        text: "pattern webapp/dist/.*: no matching files found"