version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

issues:
  exclude-rules:
    - text: "pattern webapp/dist/.*: no matching files found"
      linters:
        - typecheck
    - linters:
        - staticcheck
      text: "ST1001"