package design

import . "goa.design/goa/v3/dsl"

var _ = Service("Module", func() {
	HTTP(func() {
		Path("/api/modules")
	})
	Method("ListModules", func() {
		Description("List the model modules in the current Go workspace")
		Result(ArrayOf(Module))
		HTTP(func() {
			GET("/")
			Response(StatusOK)
		})
	})
	Method("Subscribe", func() {
		Description("WebSocket endpoint for subscribing to updates to the model")
		Payload(Module)
		StreamingResult(Model)
		HTTP(func() {
			GET("/subscribe")
			Param("GoMod:mod")
			Response(StatusSwitchingProtocols)
		})
	})
	Method("GetModel", func() {
		Description("Stream the model JSON, see https://pkg.go.dev/goa.design/model/mdl#Model")
		Payload(Module)
		HTTP(func() {
			GET("/model")
			Param("GoMod:mod")
			SkipResponseBodyEncodeDecode()
		})
	})
	Method("Compile", func() {
		Description("Stream the model DSL, save it, compile it and return the corresponding JSON")
		Payload(Module)
		Result(Model)
		Error("compilation_failed", ErrorResult, "Compilation failed")
		HTTP(func() {
			POST("/compile")
			Param("GoMod:mod")
			SkipRequestBodyEncodeDecode()
			Response(StatusOK)
			Response("compilation_failed", StatusBadRequest)
		})
	})
	Method("GetLayout", func() {
		Description("Stream the model layout JSON saved in the SVG")
		Payload(Module)
		HTTP(func() {
			GET("/layout")
			Param("GoMod:mod")
			SkipResponseBodyEncodeDecode()
		})
	})
	Method("WriteDiagram", func() {
		Description("Save the SVG streamed in the request body")
		Payload(Module)
		HTTP(func() {
			POST("/diagram")
			Param("GoMod:mod")
			SkipRequestBodyEncodeDecode()
			Response(StatusNoContent)
		})
	})
})

var Module = Type("Module", func() {
	Attribute("GoMod", String, "Design Go module", func() {
		domainRegex := `^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}`
		orgRegex := `[a-zA-Z0-9_\-]+`
		pathRegex := `(/([a-zA-Z0-9_\-]+))*$`
		Pattern(domainRegex + "/" + orgRegex + "/" + pathRegex)
		Example("goa.design/model/examples/basic/model")
	})
	Required("GoMod")
})

var Model = Type("Model", String, func() {
	Format(FormatJSON)
	Docs(func() {
		Description("A serialized representation of a model")
		URL("https://pkg.go.dev/goa.design/model/mdl#Model")
	})
})

var Layout = Type("Layout", String, func() {
	Format(FormatJSON)
	Docs(func() {
		Description("A serialized representation of a model layout as generated by the UI in the SVG")
	})
})
